#include "Visual/ALSAEQARuntimeVisualComponent.h"
#include "Components/PointLightComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/StaticMesh.h"
#include "GameFramework/Actor.h"
UALSAEQARuntimeVisualComponent::UALSAEQARuntimeVisualComponent(){PrimaryComponentTick.bCanEverTick=true;}
void UALSAEQARuntimeVisualComponent::BeginPlay(){Super::BeginPlay();if(bBuildOnBeginPlay)RebuildVisual();}
void UALSAEQARuntimeVisualComponent::TickComponent(float D,ELevelTick T,FActorComponentTickFunction* F){Super::TickComponent(D,T,F);VisualTime+=D;AActor* O=GetOwner();if(!O)return;float Bob=FMath::Sin(VisualTime*3.0f)*2.5f;for(USceneComponent* P:VisualParts)if(IsValid(P)){FVector L=P->GetRelativeLocation();if(P!=O->GetRootComponent())P->SetRelativeLocation(FVector(L.X,L.Y,L.Z+Bob*D*3.0f));}if(VisualRole==EALSAEQAVisualRole::Hero||VisualRole==EALSAEQAVisualRole::Boss){if(FMath::Sin(VisualTime*7.0f)>0.97f){} }}
void UALSAEQARuntimeVisualComponent::ClearVisual(){for(USceneComponent* P:VisualParts)if(IsValid(P))P->DestroyComponent();VisualParts.Reset();}
void UALSAEQARuntimeVisualComponent::AddMesh(const TCHAR* Path,const FVector& L,const FVector& S,const FRotator& R){AActor* O=GetOwner();if(!O||!O->GetRootComponent())return;UStaticMesh* M=Cast<UStaticMesh>(StaticLoadObject(UStaticMesh::StaticClass(),nullptr,Path));if(!M)return;UStaticMeshComponent* C=NewObject<UStaticMeshComponent>(O);if(!C)return;C->SetStaticMesh(M);C->SetCollisionEnabled(ECollisionEnabled::NoCollision);C->SetMobility(EComponentMobility::Movable);C->AttachToComponent(O->GetRootComponent(),FAttachmentTransformRules::KeepRelativeTransform);C->SetRelativeLocation(L);C->SetRelativeScale3D(S);C->SetRelativeRotation(R);C->RegisterComponent();VisualParts.Add(C);}
void UALSAEQARuntimeVisualComponent::AddWeaponVisual(){if(VisualRole==EALSAEQAVisualRole::Hero||VisualRole==EALSAEQAVisualRole::Companion){AddMesh(TEXT("/Engine/BasicShapes/Cylinder.Cylinder"),FVector(42,0,35),FVector(.12f,.12f,.85f),FRotator(0,0,-35));AddMesh(TEXT("/Engine/BasicShapes/Cube.Cube"),FVector(28,0,8),FVector(.45f,.16f,.1f),FRotator::ZeroRotator);}else if(VisualRole==EALSAEQAVisualRole::Enemy||VisualRole==EALSAEQAVisualRole::Boss)AddMesh(TEXT("/Engine/BasicShapes/Cube.Cube"),FVector(46,0,30),FVector(.12f,.38f,.95f),FRotator(0,0,-30));}
void UALSAEQARuntimeVisualComponent::AddStormVisual(){if(!bAddStormLight||(VisualRole!=EALSAEQAVisualRole::Hero&&VisualRole!=EALSAEQAVisualRole::Boss))return;AActor* O=GetOwner();if(!O||!O->GetRootComponent())return;UPointLightComponent* L=NewObject<UPointLightComponent>(O);if(!L)return;L->SetMobility(EComponentMobility::Movable);L->SetIntensity(900);L->SetAttenuationRadius(420);L->SetLightColor(FLinearColor(.25f,.55f,1));L->AttachToComponent(O->GetRootComponent(),FAttachmentTransformRules::KeepRelativeTransform);L->SetRelativeLocation(FVector(0,0,120));L->RegisterComponent();VisualParts.Add(L);}
void UALSAEQARuntimeVisualComponent::RebuildVisual(){ClearVisual();switch(VisualRole){case EALSAEQAVisualRole::Hero:AddMesh(TEXT("/Engine/BasicShapes/Cylinder.Cylinder"),FVector(0,0,70),FVector(.38f,.38f,.75f),FRotator::ZeroRotator);AddMesh(TEXT("/Engine/BasicShapes/Sphere.Sphere"),FVector(0,0,145),FVector(.38f),FRotator::ZeroRotator);break;case EALSAEQAVisualRole::Companion:AddMesh(TEXT("/Engine/BasicShapes/Cylinder.Cylinder"),FVector(0,0,68),FVector(.34f,.34f,.70f),FRotator::ZeroRotator);AddMesh(TEXT("/Engine/BasicShapes/Sphere.Sphere"),FVector(0,0,140),FVector(.36f),FRotator::ZeroRotator);break;case EALSAEQAVisualRole::Enemy:AddMesh(TEXT("/Engine/BasicShapes/Cylinder.Cylinder"),FVector(0,0,70),FVector(.48f,.48f,.82f),FRotator::ZeroRotator);AddMesh(TEXT("/Engine/BasicShapes/Sphere.Sphere"),FVector(0,0,150),FVector(.43f),FRotator::ZeroRotator);break;case EALSAEQAVisualRole::Boss:AddMesh(TEXT("/Engine/BasicShapes/Cylinder.Cylinder"),FVector(0,0,105),FVector(.82f,.82f,1.25f),FRotator::ZeroRotator);AddMesh(TEXT("/Engine/BasicShapes/Sphere.Sphere"),FVector(0,0,220),FVector(.70f),FRotator::ZeroRotator);break;case EALSAEQAVisualRole::Snake:AddMesh(TEXT("/Engine/BasicShapes/Cylinder.Cylinder"),FVector(0,0,55),FVector(.72f,.72f,1.6f),FRotator(0,0,90));AddMesh(TEXT("/Engine/BasicShapes/Sphere.Sphere"),FVector(85,0,70),FVector(.8f,.58f,.58f),FRotator::ZeroRotator);break;case EALSAEQAVisualRole::Mount:AddMesh(TEXT("/Engine/BasicShapes/Cylinder.Cylinder"),FVector(0,0,70),FVector(.72f,.48f,.75f),FRotator(0,90,0));AddMesh(TEXT("/Engine/BasicShapes/Sphere.Sphere"),FVector(105,0,105),FVector(.42f,.32f,.32f),FRotator::ZeroRotator);break;case EALSAEQAVisualRole::Weapon:AddMesh(TEXT("/Engine/BasicShapes/Cylinder.Cylinder"),FVector(0,0,50),FVector(.1f,.1f,1),FRotator::ZeroRotator);break;}if(bAddWeapon)AddWeaponVisual();AddStormVisual();}
void UALSAEQARuntimeVisualComponent::SetVisualRole(EALSAEQAVisualRole N){VisualRole=N;if(IsRegistered())RebuildVisual();}
